// src/views/Bookmark.vue
<template>
  <div @keyup.enter="save()">
    <header style="padding-left: 20px">
      <h3>{{ mode }} Bookmark</h3>
      <hr />
    </header>
    <div class="form" :class="{ 'was-validated': validated }">
      <div class="form-group">
        <label for="bookmark">Bookmark</label>
        <input
          class="form-control"
          v-model.trim="name"
          id="bookmark"
          maxlength="40"
          required
        />
        <div class="invalid-feedback">This field is required.</div>
        <small class="form-text text-muted">Max length: 40 characters.</small>
      </div>
      <div class="form-group">
        <label for="url">URL</label>
        <input
          class="form-control"
          type="url"
          v-model.trim="url"
          id="url"
          @blur="chkURL"
          required
        />
        <div class="invalid-feedback">Please enter a valid URL.</div>
      </div>
      <div class="form-group">
        <label for="category">Category</label>
        <input
          class="form-control"
          list="category-list"
          v-model.trim="category"
          id="category"
          maxlength="15"
        />
        <datalist id="category-list">
          <option v-for="c in categories" :key="c.id">{{ c.name }}</option>
        </datalist>
        <small class="form-text text-muted"
          >Max length: 15 characters. One chinese character equal three
          characters.</small
        >
      </div>
      <button class="btn btn-primary" @click="save()">{{ mode }}</button>
      <button class="btn btn-primary" @click="goback()">Cancel</button>
    </div>
    <div class="form" v-if="mode == 'Edit'">
      <button class="btn btn-danger delete" @click="del()">Delete</button>
    </div>
  </div>
</template>

<script>
import { BootstrapButtons, post, valid, confirm } from "../misc.js";

export default {
  name: "Bookmark",
  data() {
    return {
      categories: this.$store.state.categories,
      bookmark: this.$store.state.bookmark,
      name: "",
      url: "",
      category: "",
      validated: false,
    };
  },
  computed: {
    mode() {
      return this.$route.params.mode == "add" ? "Add" : "Edit";
    },
  },
  created() {
    this.name = this.bookmark.name;
    this.url = this.bookmark.url;
    this.category = this.bookmark.category;
  },
  mounted() {
    document.title = this.mode + " Bookmark - My Bookmarks";
    window.addEventListener("keyup", this.cancel);
  },
  beforeUnmount: function () {
    window.removeEventListener("keyup", this.cancel);
  },
  methods: {
    chkURL() {
      if (this.url && !this.url.match(/^https?:/) && this.url.length)
        this.url = "http://" + this.url;
    },
    async save() {
      if (valid()) {
        this.validated = false;
        let resp;
        if (this.mode == "Add")
          resp = await post("/bookmark/add", {
            name: this.name,
            url: this.url,
            category: this.category,
          });
        else
          resp = await post("/bookmark/edit/" + this.bookmark.id, {
            name: this.name,
            url: this.url,
            category: this.category,
          });
        if (!resp.ok)
          await BootstrapButtons.fire("Error", await resp.text(), "error");
        else {
          const json = await resp.json();
          if (json.status == 1) {
            await this.goback(true);
            await this.$store.dispatch("bookmarks", {
              id: this.$store.state.category.id,
            });
          } else {
            await BootstrapButtons.fire("Error", json.message, "error");
            if (json.error == 1) this.name = "";
            else if (json.error == 2) this.url = "";
          }
        }
      } else this.validated = true;
    },
    async del() {
      if (await confirm("bookmark")) {
        const resp = await post("/bookmark/delete/" + this.bookmark.id);
        if (!resp.ok)
          await BootstrapButtons.fire("Error", await resp.text(), "error");
        else {
          await this.$store.dispatch("delBookmarks", this.bookmark);
          this.goback();
        }
      }
    },
  },
};
</script>

// src/components/Bookmark.svelte
<script lang="ts">
  import { fire, post, valid, confirm } from "../misc";
  import { component, bookmark, categories, bookmarks, total } from "../stores";

  let name = $bookmark ? $bookmark.bookmark : "";
  let url = $bookmark ? $bookmark.url : "";
  let category = $bookmark ? $bookmark.category : "";
  let validated = false;

  $: mode = window.location.pathname == "/bookmark/add" ? "Add" : "Edit";

  const chkURL = () => {
    if (url && !url.match(/^https?:/) && url.length) url = "http://" + url;
  };

  const save = async () => {
    if (valid()) {
      validated = false;
      if (!category) category = "";
      let resp: Response;
      if (mode == "Add")
        resp = await post("/bookmark/add", { bookmark: name, url, category });
      else
        resp = await post("/bookmark/edit/" + $bookmark.id, {
          bookmark: name,
          url,
          category,
        });
      if (!resp.ok) await fire("Error", await resp.text(), "error");
      else {
        const json = await resp.json();
        if (json.status == 1) {
          if (mode == "Add") {
            $bookmarks = [
              ...$bookmarks,
              {
                id: json.id,
                bookmark: name,
                url,
                category,
                seq: $bookmarks.length + 1,
              },
            ];
            const index = $categories.findIndex(
              (c) => c.category === $bookmark.category
            );
            if (index !== -1) $categories[index].count++;
            else if (json.cid)
              $categories.push({ id: json.cid, category, count: 1 });
            $total++;
          } else {
            if (category) {
              const index = $categories.findIndex(
                (c) => c.category === category
              );
              if (index !== -1) $categories[index].count++;
              else $categories.push({ id: json.cid, category, count: 1 });
            }
            if ($bookmark.category)
              $categories[
                $categories.findIndex((c) => c.category === $bookmark.category)
              ].count--;
            const index = $bookmarks.findIndex((b) => b.id === $bookmark.id);
            $bookmarks[index].bookmark = name;
            $bookmarks[index].url = url;
            $bookmarks[index].category = category;
          }
          goback();
        } else {
          await fire("Error", json.message, "error");
          if (json.error == 1) name = "";
          else if (json.error == 2) url = "";
        }
      }
    } else validated = true;
  };

  const del = async () => {
    if (await confirm("bookmark")) {
      const resp = await post("/bookmark/delete/" + $bookmark.id);
      if (!resp.ok) await fire("Error", await resp.text(), "error");
      else {
        const index = $bookmarks.findIndex((b) => b.id === $bookmark.id);
        $bookmarks.splice(index, 1);
        $bookmarks.forEach((b) => {
          if (b.seq > $bookmark.seq) b.seq++;
        });
        if ($bookmark.category)
          $categories[
            $categories.findIndex((c) => c.category === $bookmark.category)
          ].count--;
        $total--;
        goback();
      }
    }
  };

  const goback = () => {
    window.history.pushState({}, "", "/");
    $component = "show";
  };
</script>

<svelte:window
  on:keydown={(e) => {
    if (e.key === "Escape") goback();
  }}
/>

<svelte:head>
  <title>{mode} Bookmark - My Bookmarks</title>
</svelte:head>

<div
  on:keydown={async (e) => {
    if (e.key == "Enter") await save();
  }}
>
  <header style="padding-left: 20px">
    <h3>{mode} Bookmark</h3>
    <hr />
  </header>
  <div class="form" class:was-validated={validated}>
    <div class="form-group">
      <label for="bookmark">Bookmark</label>
      <input
        class="form-control"
        id="bookmark"
        bind:value={name}
        maxlength="40"
        required
      />
      <div class="invalid-feedback">This field is required.</div>
      <small class="form-text text-muted">Max length: 40 characters.</small>
    </div>
    <div class="form-group">
      <label for="url">URL</label>
      <input
        class="form-control"
        id="url"
        type="url"
        bind:value={url}
        on:blur={chkURL}
        required
      />
      <div class="invalid-feedback">Please enter a valid URL.</div>
    </div>
    <div class="form-group">
      <label for="category">Category</label>
      <input
        class="form-control"
        id="category"
        list="category-list"
        bind:value={category}
        maxlength="15"
      />
      <datalist id="category-list">
        {#each $categories as category (category.id)}
          <option>{category.category}</option>
        {/each}
      </datalist>
      <small class="form-text text-muted">
        Max length: 15 characters. One chinese character equal three characters.
      </small>
    </div>
    <button class="btn btn-primary" on:click={save}>{mode}</button>
    <button class="btn btn-primary" on:click={goback}>Cancel</button>
  </div>
  {#if mode == "Edit"}
    <div class="form">
      <button class="btn btn-danger delete" on:click={del}>Delete</button>
    </div>
  {/if}
</div>

<style>
  .delete {
    margin-top: 8px;
  }
</style>
